config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  scope "(:locale)", locale: /vi|en/ do
    root "static_pages#home" 
    get "about", to: "static_pages#about"
    get "contact", to: "static_pages#contact"
    resources :courses
    resources :lessons, except: :index
    resources :homeworks
    resources :homework_details
    resources :course_users
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :homeworks
  resourcify
  scope :next_lesson, ->(lesson) { where(number: lesson.number + 1) }

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_courses, only: [:show, :new, :edit, :create]
  before_action :find_course, only: [:show, :edit, :update, :destroy]
  before_action :next_lesson, only: [:show, :index]

  def new
    @lesson = current_user.lessons.build
  end

  def create
    @lesson = current_user.lessons.build lesson_params
    @lesson.user_id = current_user.id if user_signed_in?

    if @lesson.save
      flash[:success] = t(".lesson_created")
      redirect_to lesson_path(id: @lesson.id, course_id: @lesson.course.id)
    else
      render :new
    end
  end

  def show
    @homeworks = @lesson.homeworks
  end

  def edit; end

  def update
    if @lesson.update lesson_params
      flash[:success] = t(".lesson_updated")
      redirect_to lesson_path(id: @lesson.id, course_id: @lesson.course.id)
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    flash[:success] = t(".lesson_deleted")
    redirect_to course_path
  end

  private
    def lesson_params
      params.require(:lesson).permit :title, :content, :course_id
    end

    def find_courses
      @courses = Course.all
    end

    def find_course
      @lesson = Lesson.find_by id: params[:id]
      @course = Course.find_by id: params[:course_id]
    end
    def next_lesson
      @lesson = Lesson.find_by id: params[:id]
      @next_lesson = Lesson.find_by id: (@lesson.id + 1)
    end
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <%= render "shared/errors", object: @lesson %>
  <div class="field">
    <%= f.label :title, t(".title") %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :number, t(".number") %>
    <%= f.number_field :number, class: "form-control" %>
  </div>
   <div class="field">
    <%= f.label :content, t(".content") %>
    <%= f.cktext_area :content, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <%= f.label :course, t(".course") %>
     <span>
      <%= f.select :course_id, @courses.map { |c| [c.course_name, c.id] },
        prompt: t(".select_course") %>
    </span>
  </div>

  <div class="field mt-3">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<% provide :title, t(".update_lesson") %>
<% provide :button_text, t(".update_lesson") %>

<div class="row jumbotron mt-3">
  <div class="col-md-12">
    <h1 class="text-center"><%= t(".update_lesson") %></h1>
  </div>
  <div class="col-md-12">
    <% if has_role?(:admin) %>
      <%= render "form" %>
    <% else %>
      <h5 class="text-center text-danger">
        <%= t(".sorry") %>
      </h5>
    <% end %>
  </div>
</div>

app/views/lessons/new.html.erb
<% provide :title, t(".create_lesson") %>
<% provide :button_text, t(".create_lesson") %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h4 class="text-center"><%= t(".create_lesson") %></h4>
  </div>
  <div class="col-md-12">
    <% if has_role?(:admin) %>
      <%= render "form" %>
    <% else %>
      <h5 class="text-center text-danger">
        <%= t(".sorry") %>
      </h5>
    <% end %>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h3 class="text-center"><%= @course.course_name %></h3>
  </div>
</div>
<div class="row jumbotron mt-3">
  <div class="col-md-8 offset-md-2">
    <div class="row">
      <div class="col-md-12">
       <h3 class="text-center"><%= @course.course_name %></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7 offset-md-3">
        <h5>
          <%= @lesson.title %>
        </h5>

      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>
          <%= @lesson.content.html_safe %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-7 offset-md-3">
     <% @homeworks.each do |homework| %>
      <p>
         <%= link_to homework.name, homework_path(id: homework.id) %>
      </p>
    <% end %>
  </div>
</div>
<%= link_to "next lesson", lesson_path(id: @next_lesson.id, course_id: @course.id) %>