config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  scope "(:locale)", locale: /vi|en/ do
    root "static_pages#home" 
    get "about", to: "static_pages#about"
    get "contact", to: "static_pages#contact"
    resources :courses
    resources :lessons, except: :index
    resources :homeworks
    resources :homework_details
    resources :course_users
  end
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :lesson
  has_one :homework_detail
  resourcify
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_lessons, only: [:show, :new, :edit]
  before_action :find_lesson, only: [:show, :edit, :update, :destroy]

  def new
    @homework = Homework.new
  end

  def create
    @homework = Homework.new homework_params
    if @homework.save
      flash[:success] = t(".homework_created")
      redirect_to homework_path(id: @homework.id, lesson_id: @homework.lesson.id)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
  end

  def destroy
  end

  private
    def homework_params
      params.require(:homework).permit :name, :lesson_id
    end

    def find_lessons
      @lessons = Lesson.all
    end

    def find_lesson
      @homework = Homework.find_by id: params[:id]
      @lesson = @homework.lesson
    end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <div class="field">
    <%= f.label :name, t(".name") %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   <div class="field">
    <%= f.label :question, t(".content") %>
    <%= f.cktext_area :question, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <%= f.label :lesson, t(".lesson") %>
     <span>
      <%= f.select :lesson_id, @lessons.map { |c| [c.title, c.id] },
        prompt: t(".select_lesson") %>
    </span>
  </div>

  <div class="field mt-3">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/homeworks/new.html.erb
<% provide :title, t(".create_homework") %>
<% provide :button_text, t(".create_homework") %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h4 class="text-center"><%= t(".create_homework") %></h4>
  </div>
  <div class="col-md-12">
    <% if has_role?(:admin) %>
      <%= render "form" %>
    <% else %>
      <h5 class="text-center text-danger">
        <%= t(".sorry") %>
      </h5>
    <% end %>
  </div>
</div>

app/views/homeworks/show.html.erb
<div class="row jumbotron mt-3">
  <div class="col-md-8 offset-md-2">
    <div class="row">
      <div class="col-md-12">
       <h3 class="text-center"><%= @lesson.title %></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7 offset-md-3">
        <h5>
          <%= link_to @homework.name,new_homework_detail_path(homework_id: @homework.id) %>
        </h5>

      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>
          <%= @homework.question %>
        </p>
      </div>
    </div>
  </div>
</div>