config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  scope "(:locale)", locale: /vi|en/ do
    root "static_pages#home" 
    get "about", to: "static_pages#about"
    get "contact", to: "static_pages#contact"
    resources :courses
    resources :lessons, except: :index
    resources :homeworks
    resources :homework_details
    resources :course_users
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)    
      user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_many :course_users
  belongs_to :user
  resourcify
end

app/models/course_user.rb
class CourseUser < ApplicationRecord
  belongs_to :user
  belongs_to :course
  resourcify
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :lesson
  resourcify
end

app/models/exercise_answer.rb
class ExerciseAnswer < ApplicationRecord
  belongs_to :exercise
  belongs_to :user
  resourify
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :lesson
  has_one :homework_detail
  resourcify
end

app/models/homework_detail.rb
class HomeworkDetail < ApplicationRecord
  belongs_to :homework
  belongs_to :user
  resourcify
end

app/models/homework_result.rb
class HomeworkResult < ApplicationRecord
  belongs_to :exercise_answer
  belongs_to :homeworl_detail
  resourcify
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :homeworks
  resourcify
  scope :next_lesson, ->(lesson) { where(number: lesson.number + 1) }

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

belongs_to :resource, :polymorphic => true, :optional => true

validates :resource_type, :inclusion => { :in => Rolify.resource_types },
  :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :courses
  has_many :lessons
  has_many :homework_details
  has_many :course_users
end

app/models/user_lesson.rb
class UserLesson < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  resoucify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, 
      :email, :password)}
     
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, 
      :email, :password, :current_password)}
    end

  private

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options
      { locale: I18n.locale }
    end
end

app/controllers/course_users_controller.rb
class CourseUsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def new
    @course_user = CourseUser.new(course_user_params)
  end

  def create
    @course_user = current_user.course_users.new(course_user_params)
    respond_to do |format|
      if @course_user.save
        format.html{redirect_to(@course_user.course)}
        format.js
      end
    end
  end


  def destroy
    @course_user = CourseUser.find_by(id: params[:id])
    course = @course_user.course
    respond_to do |format|
      if @course_user.destroy
        format.html{redirect_to(@course_user.course)}
      end
    end
  end

  private
  def course_user_params
    params.require(:course_users).permit(:course_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :find_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @courses = Course.all
  end

  def new
    @course = current_user.courses.build
  end

  def create
    @course = current_user.courses.build course_params
    if @course.save
      flash[:success] = t(".course_created")
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @lessons = @course.lessons
  end

  def edit; end

  def update
    if @course.save
      flash[:success] = t(".course_updated")
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    flash[:danger] = t(".course_deleted")
    redirect_to @course
  end

  private

    def course_params
      params.require(:course).permit :course_name, :description
    end

    def find_course
      @course = Course.find_by id: params[:id]
      unless @course
        flash[:danger] = t(".does_not")
        redirect_to root_path
      end
    end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_lessons, only: [:show, :new, :edit]
  before_action :find_lesson, only: [:show, :edit, :update, :destroy]

  def new
    @homework = Homework.new
  end

  def create
    @homework = Homework.new homework_params
    if @homework.save
      flash[:success] = t(".homework_created")
      redirect_to homework_path(id: @homework.id, lesson_id: @homework.lesson.id)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
  end

  def destroy
  end

  private
    def homework_params
      params.require(:homework).permit :name, :lesson_id
    end

    def find_lessons
      @lessons = Lesson.all
    end

    def find_lesson
      @homework = Homework.find_by id: params[:id]
      @lesson = @homework.lesson
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_courses, only: [:show, :new, :edit, :create]
  before_action :find_course, only: [:show, :edit, :update, :destroy]
  before_action :next_lesson, only: [:show, :index]

  def new
    @lesson = current_user.lessons.build
  end

  def create
    @lesson = current_user.lessons.build lesson_params
    @lesson.user_id = current_user.id if user_signed_in?

    if @lesson.save
      flash[:success] = t(".lesson_created")
      redirect_to lesson_path(id: @lesson.id, course_id: @lesson.course.id)
    else
      render :new
    end
  end

  def show
    @homeworks = @lesson.homeworks
  end

  def edit; end

  def update
    if @lesson.update lesson_params
      flash[:success] = t(".lesson_updated")
      redirect_to lesson_path(id: @lesson.id, course_id: @lesson.course.id)
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    flash[:success] = t(".lesson_deleted")
    redirect_to course_path
  end

  private
    def lesson_params
      params.require(:lesson).permit :title, :content, :course_id
    end

    def find_courses
      @courses = Course.all
    end

    def find_course
      @lesson = Lesson.find_by id: params[:id]
      @course = Course.find_by id: params[:course_id]
    end
    def next_lesson
      @lesson = Lesson.find_by id: params[:id]
      @next_lesson = Lesson.find_by id: (@lesson.id + 1)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @courses = Course.order("created_at desc").limit(6)
  end

  def help; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def has_role?(role)
    current_user && current_user.has_role?(role)
  end

  def full_title page_title = ""
    base_title = "Training system"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <%= render "shared/errors", object: @course %>
  <div class="field">
    <%= f.label :course_name, t(".course_name") %>
    <%= f.text_field :course_name, class: "form-control" %>
  </div>
  <div class="field mt-3">
    <%= f.label :description, t(".description") %>
    <%= f.cktext_area :description, class: "form-control" %>
  </div>
  <div class="field mt-2">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<% provide :title, t(".update_course") %>
<% provide :button_text,  t(".update_course") %>

<div class="row jumbotron mt-3">
  <div class="col-md-12">
    <h2 class="text-center"><%= t(".update_course") %></h2>
  </div>
  <div class="col-md-12">
    <% if has_role?(:admin) %>
      <%= render "form" %>
    <% else %>
      <h5 class="text-center text-danger">
        <%= t(".sorry") %>
      </h5>
    <% end %>
  </div>
</div>

app/views/courses/index.html.erb
<!-- Featured Projects-->
<section class="section section-lg bg-default text-center padding-top-15">
  <div class="container">
    <h2 class="wow fadeIn"><%= t(".all_course") %></h2>
    <% if has_role?(:admin) %>
      <%= link_to t(".new_course"), new_course_path,
        class: "btn btn-outline-primary float-right" %>
    <% end %>
    <div class="row row-30 row-md-50 row-xl-70">
      <% @courses.each do |course| %>
        <div class="col-sm-6 col-lg-4 wow fadeIn">
          <!-- Post Minimal-->
          <div class="post-minimal">
            <figure class="post-minimal-media">
              <%= link_to course.description.html_safe, course,
                class: "text-muted image-course" %>
            </figure>
            <h4 class="post-minimal-title"><a href="#"><%= link_to course.course_name, course %></a></h4>
            </p>
            <% if has_role?(:admin) %>
              <%= link_to t(".edit_course"), edit_course_path(course),
                class: "btn btn-outline-secondary" %>
              <%= link_to t(".delete_course"), course, method: :delete,
                data: { confirm: "Are you sure?" },
                class: "btn btn-outline-danger" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/courses/new.html.erb
<% provide :title, t(".create_course") %>
<% provide :button_text,  t(".create_course") %>

<div class="row jumbotron mt-3">
  <div class="col-md-12">
    <h2 class="text-center"><%= t(".create_course") %></h2>
  </div>
  <div class="col-md-12">
    <% if has_role?(:admin) %>
      <%= render "form" %>
    <% else %>
      <h5 class="text-center text-danger">
        <%= t(".sorry") %>
      </h5>
    <% end %>
  </div>
</div>

app/views/courses/show.html.erb
<div class="row jumbotron mt-3">
  <div class="col-md-12">
    <%= link_to "Back", root_path, 
      class: "btn btn-sm btn-outline-primary mb-1" %>
  </div>
  <div class="col-md-8 offset-md-2">
    <div class="row">
      <div class="col-md-9">
        <h3>
          <%= @course.course_name %>
        </h3>
      </div>
      <div class="col-md-3">
        <% if has_role?(:admin) %>
          <%= link_to "Create lesson", new_lesson_path,
            class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7 offset-md-1">
        <% @lessons.each do |lesson| %>
          <div class="row">
            <div class="col-md-3">
              <%= link_to lesson.title,
                lesson_path(id: lesson.id, course_id: @course.id) %>
            </div>
            <div class="col-md-9 mt-2">
              <% if has_role?(:admin) %>
                <%= link_to "Edit lesson",
                  edit_lesson_path(id: lesson.id, course_id: @course.id),
                  class: "btn btn-outline-secondary" %>
                <%= link_to "Delete lesson", lesson, method: :delete,
                  class: "btn btn-outline-danger" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  <% if current_user.course_users.find_by(course_id: @course.id) %>
    <%= link_to "End",course_user_path(current_user.course_users.find_by(course_id: @course.id)),method: :delete %>
  <% else %>
    <%= link_to "Learn",course_users_path(course_users: {course_id: @course.id}), method: :post %>

  <% end %>

app/views/static_pages/about.html.erb
<!-- My Approach-->
<section class="section section-lg bg-default">
  <div class="container">
    <div class="row row-50 justify-content-center justify-content-xl-between flex-lg-row-reverse">
      <div class="col-md-11 col-lg-6 col-xl-5">
        <div class="box-1">
          <h2>Vài Từ Mô Tả Trung Tâm Online</h2>
          <h5>Nơi Đây Bạn Có Thể Học Mọi Lúc, Mọi Nơi</h5>
          <p>Tại Trung tâm online, chúng tôi hướng đến cung cấp chất lượng cao về 
            học tập, đảm bảo kiến thức cần thiết cho người học đi xin việc. Các 
            khoá học được cung cấp bởi các giảng viên có kinh nghiệm về giáo dục
          </p>
        </div>
      </div>
      <div class="col-md-11 col-lg-6">
        <!-- Thumbnail Media-->
        <div>
          <%= image_tag("ngon-ngu.jpg", class: "img-fluid") %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Services-->
<section class="section section-lg bg-gray-100 text-center">
  <div class="container">
    <h2 class="wow fadeIn">Các Khoá Học</h2>
    <p class="wow fadeIn" data-wow-delay=".2s">
      <span class="text-gray-900" style="max-width: 570px;">
        Tại Trung Tâm Online, bạn sẽ tìm được rất nhiều khoá học phù hợp cho
        mình, để nâng cao khả năng bản thân cũng như kỹ năng làm việc.
      </span>
    </p>
    <div class="row row-30 row-xl-90 justify-content-center">
      <div class="col-sm-6 col-lg-4 col-xl-3 wow fadeIn" data-wow-delay=".2s">
        <!-- Box Classic-->
        <article class="box-classic"><a class="fa fa-html5 icon box-classic-icon linearicons-calculator2" href="#"></a><a class="box-classic-main" href="#">
            <h4 class="box-classic-title">HTML - CSS</h4>
            <div class="box-classic-inner">
              <p>Nắm vững các kỹ năng HTML - CSS</p>
            </div></a></article>
      </div>
      <div class="col-sm-6 col-lg-4 col-xl-3 wow fadeIn" data-wow-delay=".3s">
        <!-- Box Classic-->
        <article class="box-classic"><a class="fa fa-tasks icon box-classic-icon linearicons-briefcase" href="#"></a><a class="box-classic-main" href="#">
            <h4 class="box-classic-title">Ruby</h4>
            <div class="box-classic-inner">
              <p>Tìm hiểu lập trình ngôn ngữ Ruby</p>
            </div></a></article>
      </div>
      <div class="col-sm-6 col-lg-4 col-xl-3 wow fadeIn" data-wow-delay=".4s">
        <!-- Box Classic-->
        <article class="box-classic"><a class="far fa-laptop icon box-classic-icon linearicons-laptop-phone" href="#"></a><a class="box-classic-main" href="#">
            <h4 class="box-classic-title">Công Nghệ Máy Tính</h4>
            <div class="box-classic-inner">
              <p>Khám phá thế giới CNTT, lập trình và công nghệ máy tính.</p>
            </div></a></article>
      </div>
      <div class="col-sm-6 col-lg-4 col-xl-3 wow fadeIn" data-wow-delay=".5s">
        <!-- Box Classic-->
        <article class="box-classic"><a class="fa fa-microchip icon box-classic-icon linearicons-chip" href="#"></a><a class="box-classic-main" href="#">
            <h4 class="box-classic-title">Ruby on Rails</h4>
            <div class="box-classic-inner">
              <p>Tìm hiểu làm thế nào để bảo trì và sửa chữa các thiết bị điện tử hiện đại.</p>
            </div></a></article>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contact.html.erb
<!-- Mailform-->
<section class="section section-lg bg-default">
  <div class="container">
    <div class="row row-50 justify-content-xl-between flex-lg-row-reverse">
      <div class="col-lg-4 col-xl-3">
        <div class="row row-30 row-xl-60">
          <div class="col-sm-4 col-lg-12">
            <h4>Địa Chỉ</h4>
            <p class="offset-top-1"><a class="link-default" href="#">Awesome Academy, Tầng 11 Handico Tower khu đô thị mới Mễ Trì Hạ, đường Phạm Hùng, quận Nam Từ Liêm, Hà Nội <br class="d-none d-md-block"></a></p>
          </div>
          <div class="col-sm-4 col-lg-12">
            <h4>Số Điện Thoại</h4>
            <ul class="list-0 offset-top-1">
              <li><a class="link-default" href="tel:#">1-800-1234-567</a></li>
              <li><a class="link-default" href="tel:#">1-800-8764-098</a></li>
            </ul>
          </div>
          <div class="col-sm-4 col-lg-12">
            <h4>E-mails</h4>
            <ul class="list-0 offset-top-1">
              <li><a class="link-default" href="mailto:#">info@demolink.org</a></li>
              <li><a class="link-default" href="mailto:#">mail@demolink.org</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <h2>Liên Lạc</h2>
        <!-- RD Mailform-->
        <form class="rd-form rd-mailform" data-form-output="form-output-global" data-form-type="contact" method="post" action="bat/rd-mailform.php">
          <div class="row row-30">
            <div class="col-md-6">
              <div class="form-wrap">
                <input class="form-input" id="contact-first-name" type="text" name="first-name" data-constraints="@Required">
                <label class="form-label" for="contact-first-name">Họ </label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-wrap">
                <input class="form-input" id="contact-last-name" type="text" name="last-name" data-constraints="@Required">
                <label class="form-label" for="contact-last-name">Tên</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-wrap">
                <label class="form-label" for="contact-email">E-mail</label>
                <input class="form-input" id="contact-email" type="email" name="email" data-constraints="@Required @Email">
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-wrap">
                <label class="form-label" for="contact-phone">Số Điện Thoại</label>
                <input class="form-input" id="contact-phone" type="text" name="phone" data-constraints="@Required @PhoneNumber">
              </div>
            </div>
            <div class="col-12">
              <div class="form-wrap">
                <label class="form-label" for="contact-message">Tin nhắn</label>
                <textarea class="form-input" id="contact-message" name="message" data-constraints="@Required"></textarea>
              </div>
            </div>
            <div class="col-12">
              <button class="button button-lg button-primary button-raven" type="submit">Gửi</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
<div id="carouselExampleCaptions" class="carousel slide h-carousel" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("img-bg-1.jpg", class: "d-block w-100 image-gray ") %>
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-warning display-4">Nhiều Chương Trình Đào Tạo Đang Chờ Bạn</h5>
        <p class="text-warning">
          Học viên được cung cấp kiến thức bởi các chuyên gia giáo dục hàng đầu
        </p>
        <%= link_to "Đăng ký ngay!", new_user_registration_path, 
          class: "btn btn-primary mt-5" %>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag("img-bg-2.jpg", class: "d-block w-100 image-gray") %>
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-warning display-4">Chất Lượng Đỉnh Cao Của Giáo Dục</h5>
        <p class="text-warning">
          Rất nhiều học viên đã thành công với môi trường giáo dục tốt của chúng tôi
        </p>
        <%= link_to "Đăng ký ngay!", new_user_registration_path, 
          class: "btn btn-primary mt-5" %>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag("img-bg-3.jpg", class: "d-block w-100 image-gray") %>
      <div class="carousel-caption d-none d-md-block">
        <h5 class="text-warning display-4">Cộng Đồng Học Cùng</h5>
        <p class="text-warning">
          Trở thành một phần của chúng tôi và kết nối bạn bè
        </p>
        <%= link_to "Đăng ký ngay!", new_user_registration_path, 
          class: "btn btn-primary mt-5" %>
      </div>
    </div>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">
  <section class="section section-lg bg-gray-100">
    <div class="container">
      <div class="row row-50 justify-content-center justify-content-lg-between">
        <div class="col-12">
          <h3 class="h-custom-1 f1">Một Vài Điều Về Chúng Tôi</h3>
        </div>
        <div class="col-md-6 col-lg-5 col-xl-3 wow fadeIn">
          <p>
            Tại Trung tâm online, chúng tôi hướng đến cung cấp chất lượng cao về 
            học tập, đảm bảo kiến thức cần thiết cho người học đi xin việc. Các 
            khoá học được cung cấp bởi các giảng viên có kinh nghiệm về giáo dục
          </p>
          <%= link_to "Đọc tiếp", about_path, class: "button button-primary" %>
        </div>
        <div class="col-md-6 col-xl-3 wow fadeIn" data-wow-delay=".2s">
          <!-- Linear progress bar-->
          <article class="progress-linear">
            <div class="progress-header">
              <p>Ngôn Ngữ Ruby</p><span class="progress-value">75</span>
            </div>
            <div class="progress-bar-linear-wrap">
              <div class="progress-bar-linear"></div>
            </div>
          </article>
          <!-- Linear progress bar-->
          <article class="progress-linear">
            <div class="progress-header">
              <p>Rails</p><span class="progress-value">33</span>
            </div>
            <div class="progress-bar-linear-wrap">
              <div class="progress-bar-linear"></div>
            </div>
          </article>
          <!-- Linear progress bar-->
          <article class="progress-linear">
            <div class="progress-header">
              <p>Kỹ Thuật Máy Tính</p><span class="progress-value">88</span>
            </div>
            <div class="progress-bar-linear-wrap">
              <div class="progress-bar-linear"></div>
            </div>
          </article>
          <!-- Linear progress bar-->
          <article class="progress-linear">
            <div class="progress-header">
              <p>Lập Trình</p><span class="progress-value">75</span>
            </div>
            <div class="progress-bar-linear-wrap">
              <div class="progress-bar-linear"></div>
            </div>
          </article>
          <!-- Linear progress bar-->
          <article class="progress-linear">
            <div class="progress-header">
              <p>Điện Tử</p><span class="progress-value">50</span>
            </div>
            <div class="progress-bar-linear-wrap">
              <div class="progress-bar-linear"></div>
            </div>
          </article>
        </div>
        <div class="col-xl-4 wow fadeIn" data-wow-delay=".4s">
          <%= image_tag("students.jpg") %>
        </div>
      </div>
    </div>
  </section>
</div>

<div class="container jumbotron">
  <!-- Featured Projects-->
  <section class="section section-lg bg-default text-center">
    <div class="container">
      <h2 class="wow fadeIn">Các Khoá Học</h2>
      <div class="row row-30 row-md-50 row-xl-70">
        <% @courses.each do |course| %>
          <div class="col-sm-6 col-lg-4 wow fadeIn">
            <!-- Post Minimal-->
            <div class="post-minimal">
              <figure class="post-minimal-media">
                <%= link_to course.description.html_safe, course,
                  class: "text-muted image-course" %>
              </figure>
              <h4 class="post-minimal-title"><a href="#"><%= link_to course.course_name, course %></a></h4>
              </p>
            </div>
          </div>
        <% end %>
      </div>
        <%= link_to "Xem Toàn Bộ Các Khoá Học", courses_path, class: "button button-lg button-primary wow fadeIn" %>
    </div>
  </section>
</div>

<div class="container">
  <!-- Latest Blog Posts-->
  <section class="section section-lg bg-default text-center">
    <div class="container">
      <h2 class="wow fadeIn">Các Các Bài Viết</h2>
      <div class="row row-30 justify-content-center">
        <div class="col-sm-10 col-md-6 wow fadeIn">
          <!-- Post Light--><a class="post-light context-dark" href="#" style="background-image: url(images/grid-blog-1-570x350.jpg);">
            <div class="post-light-inner">
              <div class="badge">News</div>
              <div class="post-light-main">
                <time class="post-light-time" datetime="2019">July 5, 2020, at 12:07 pm</time>
                <h4 class="post-light-title">Campus Opening Convocation</h4>
              </div>
            </div></a>
        </div>
        <div class="col-sm-10 col-md-6 wow fadeIn" data-wow-delay=".2s">
          <!-- Post Light--><a class="post-light context-dark" href="#" style="background-image: url(images/grid-blog-2-570x350.jpg);">
            <div class="post-light-inner">
              <div class="badge">News</div>
              <div class="post-light-main">
                <time class="post-light-time" datetime="2019">July 5, 2020, at 12:07 pm</time>
                <h4 class="post-light-title">Freshman Matriculation Ceremony at Bradston College</h4>
              </div>
            </div></a>
        </div>
        <div class="col-sm-10 col-md-6 wow fadeIn">
          <!-- Post Light--><a class="post-light context-dark" href="#" style="background-image: url(images/grid-blog-3-570x350.jpg);">
            <div class="post-light-inner">
              <div class="badge">News</div>
              <div class="post-light-main">
                <time class="post-light-time" datetime="2019">July 5, 2020, at 12:07 pm</time>
                <h4 class="post-light-title">Bradston College Leadership Academy</h4>
              </div>
            </div></a>
        </div>
        <div class="col-sm-10 col-md-6 wow fadeIn" data-wow-delay=".2s">
          <!-- Post Light--><a class="post-light context-dark" href="#" style="background-image: url(images/grid-blog-4-570x350.jpg);">
            <div class="post-light-inner">
              <div class="badge">News</div>
              <div class="post-light-main">
                <time class="post-light-time" datetime="2019">July 5, 2020, at 12:07 pm</time>
                <h4 class="post-light-title">Incoming Freshmen Gather for Blueprints: Photo Gallery</h4>
              </div>
            </div></a>
        </div>
      </div><a class="button button-lg button-primary-gradient wow fadeIn" href="#" data-wow-delay=".2s"><span>View all blog posts</span></a>
    </div>
  </section>
</div>